import {
  WarningCircle,
  CalendarBlank,
  CalendarCheck,
  CheckCircle,
  ClipboardText,
  Heart,
  Info,
  ArrowsClockwise,
  Timer,
  Trophy,
  SoccerBall,
  PingPong,
  Clock,
  MapPin,
  WifiX,
  CloudArrowUp,
} from "@phosphor-icons/react/dist/ssr";

export const ICONS = {
  "alert-circle": WarningCircle,
  "arrows-clockwise": ArrowsClockwise,
  calendar: CalendarBlank,
  "calendar-check": CalendarCheck,
  "check-circle": CheckCircle,
  clipboard: ClipboardText,
  "cloud-arrow-up": CloudArrowUp,
  clock: Clock,
  football: SoccerBall,
  heart: Heart,
  info: Info,
  location: MapPin,
  "ping-pong": PingPong,
  repeat: ArrowsClockwise,
  timer: Timer,
  trophy: Trophy,
  "wifi-x": WifiX,
} as const;

export type IconName = keyof typeof ICONS;
